# -*- coding: utf-8 -*-
"""solution2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XzxLUPFyBcF-K8MMTpGAU9FmcQYuZe4z
"""

class LittleBell():
  def sound(self):
    print('ding')